ENV['EMAIL_TO'] = 'ivan@softwarecriollo.com'
ENV['EMAIL_USER_NAME'] = 'notifications@softwarecriollo.com'
ENV['EMAIL_PASSWORD'] = 'letmein123456'
ENV['EMAIL_DOMAIN'] = 'localhost'
ENV['SUBJECT_MAIL'] = 'New lead Software Criollo'