source 'https://rubygems.org'
ruby '2.2.2'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-assetpack', :require => 'sinatra/assetpack'
gem 'sinatra-flash'
gem 'sinatra-minify', '~> 0.2.3'
gem 'slim'
gem 'haml'
gem 'activemodel', '4.0'
gem 'sass'
gem 'unicorn'
gem 'pony'